/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otumasyon;
import java.util.Random;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
public class yeni_kayit1 extends javax.swing.JFrame {
    Random rnd=new Random();
    yeni_kayit bilgi_getir;
        
    void tarihi(){
        Date now=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
        String simdi=sdf.format(now);
        tarih.setText(" "+simdi);
        
        
       
     }
    
    public yeni_kayit1() {
        initComponents();
        setAlwaysOnTop(true);
        setResizable(false);
        tarihi();
        
        
    }
    
    void buyuk_harf(){
        if(lise.getText().length()!=0){
            String deger=lise.getText().substring(0,1).toUpperCase()+lise.getText().substring(1);
          lise.setText(deger);
        }
         if(alan.getText().length()!=0)
        {
             String deger=alan.getText().substring(0,1).toUpperCase()+alan.getText().substring(1);
          alan.setText(deger);
        }  
    }
    
    public yeni_kayit1(yeni_kayit gelenbilgi)
    {
        this();
        this.bilgi_getir=gelenbilgi;
    }
     public static void BilgiYaz(String bilgi)
    {
        File file=new File("C:\\otomasyon\\depo.txt");
        try
        {
            FileOutputStream dosya=new FileOutputStream(file,true);
            dosya.write(bilgi.getBytes());
            dosya.flush();
            dosya.close();
        }
        catch(Exception ex)
        {
             ex.printStackTrace();
        }
    }
     
        public static String Ogrencino_karslastirma()
    {
        String deger1="";
        File file=new File("C:\\otomasyon\\depo.txt");
        try
        {
          Scanner giris=new Scanner(file);
          deger1=giris.nextLine();
          giris.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return deger1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        akademik1 = new javax.swing.JLabel();
        akademik2 = new javax.swing.JLabel();
        akademik3 = new javax.swing.JLabel();
        akademik4 = new javax.swing.JLabel();
        akademik5 = new javax.swing.JLabel();
        lise = new javax.swing.JTextField();
        alan = new javax.swing.JTextField();
        bitirme_tarih = new javax.swing.JTextField();
        not_ortalama = new javax.swing.JTextField();
        bolum = new javax.swing.JComboBox<>();
        akademik6 = new javax.swing.JLabel();
        kayit_tarih = new javax.swing.JComboBox<>();
        akademik7 = new javax.swing.JLabel();
        ogrenci_no_bosluk = new javax.swing.JLabel();
        akademik8 = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tarih = new javax.swing.JLabel();
        onceki = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("      ANDALUS ÜNİVERSİTESİ");

        akademik1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik1.setText("Lise adi");

        akademik2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik2.setText("lisedeki alan");

        akademik3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik3.setText("Not Ortalamasi");

        akademik4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik4.setText("Lise bitirme tarihi");

        akademik5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik5.setText("Bölüm");

        lise.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liseMouseClicked(evt);
            }
        });

        alan.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        alan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alanMouseClicked(evt);
            }
        });

        bitirme_tarih.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bitirme_tarih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bitirme_tarihMouseClicked(evt);
            }
        });
        bitirme_tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirme_tarihActionPerformed(evt);
            }
        });

        not_ortalama.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        not_ortalama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                not_ortalamaMouseClicked(evt);
            }
        });

        bolum.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        bolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dis hekimligi fakultesi", "Ilahiyat fakultesi", "Iktisadi ve idari bilimleri", "iletisim fakultesi", "saglik Bilimleri fakultesi", "Spor fakultesi", "Teknoloji falultesi/Yazilim muh.", "Teknoloji falultesi/insaat  muh.", "Teknoloji falultesi/mekatronik  muh.", "Teknoloji falultesi/adli bilisim  muh.", "Tip fakultesi", "Sosyal Bilimleri Meslek yuksekokulu " }));
        bolum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bolumMouseClicked(evt);
            }
        });

        akademik6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik6.setText("Ogrenci no");

        kayit_tarih.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        kayit_tarih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seç", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        kayit_tarih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kayit_tarihItemStateChanged(evt);
            }
        });
        kayit_tarih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayit_tarihMouseClicked(evt);
            }
        });
        kayit_tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_tarihActionPerformed(evt);
            }
        });

        akademik7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik7.setText("kayıt yılı");

        ogrenci_no_bosluk.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N

        akademik8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        akademik8.setText("  Sifre");

        sifre.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        sifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifreMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Bilgileri kayidet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tarih.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        onceki.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onceki.setForeground(new java.awt.Color(204, 0, 0));
        onceki.setText("Önceki sayfa");
        onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(akademik1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(akademik2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                    .addComponent(akademik4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lise, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(alan)
                                    .addComponent(bitirme_tarih)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(akademik3)
                                    .addComponent(akademik5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(akademik7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bolum, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(not_ortalama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kayit_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(ogrenci_no_bosluk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(akademik6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(akademik8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(sifre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onceki)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lise, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akademik4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bitirme_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(not_ortalama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bolum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kayit_tarih)
                    .addComponent(akademik7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ogrenci_no_bosluk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akademik8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayit_tarihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kayit_tarihItemStateChanged
       int index=kayit_tarih.getSelectedIndex();
       String ilk="";
       if(index<10)
       {
        ilk="0"+(index-1)+"0";  
       }
       else
       {
             ilk=(index-1)+"0";
       }
        
        String son="";
        for(int i=0;i<4;i++)
        {
           int sayi=rnd.nextInt(10);
           son=son+sayi;
        }
        String OGRENCI_NO=ilk+"54"+son;
        boolean kontrol=true;
        String ogrenciNO_matris[]=Ogrencino_karslastirma().split(";");
        for(int i=0;i<ogrenciNO_matris.length;i++)
        {
            if(ogrenciNO_matris[i].equals(OGRENCI_NO))
            {
                kontrol=false;
                break;
            }
        }
        if(kontrol){
        ogrenci_no_bosluk.setText(OGRENCI_NO);
        }
        else
        {
           ogrenci_no_bosluk.setText("Lütfen kayıt yılı geri seçiniz");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_kayit_tarihItemStateChanged

    private void bitirme_tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirme_tarihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bitirme_tarihActionPerformed

    private void kayit_tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_tarihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kayit_tarihActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean b=Pattern.matches("\\d{1,2}",not_ortalama.getText());
        if(kayit_tarih.getSelectedIndex()!=0){
        if(b)
        {
            JOptionPane.showMessageDialog(rootPane,"Bilgileri kayidedildi");
            String kayidedilecek_bilgi1=bilgi_getir.kimlikNo.getText();
            String kayidedilecek_bilgi2=bilgi_getir.ad_bos.getText();
            String kayidedilecek_bilgi22=bilgi_getir.soyad_bos.getText();
            String kayidedilecek_bilgi3=bilgi_getir.anne.getText();
            String kayidedilecek_bilgi4=bilgi_getir.baba.getText();
            String kayidedilecek_bilgi5=bilgi_getir.telefon_bos.getText();
            String kayidedilecek_bilgi6=bilgi_getir.ulke.getSelectedItem().toString();
            String kayidedilecek_bilgi7=bilgi_getir.gun.getSelectedItem().toString();
            String kayidedilecek_bilgi8=bilgi_getir.ay.getSelectedItem().toString();
            String kayidedilecek_bilgi9=bilgi_getir.yil.getSelectedItem().toString();
            String tarih=kayidedilecek_bilgi7+"/"+kayidedilecek_bilgi8+"/"+kayidedilecek_bilgi9;
            String kayidedilecek_bilgi10=lise.getText()+";"+alan.getText()+";"+bitirme_tarih.getText()+";"+not_ortalama.getText();
            String kayidedilecek_bilgi11=bolum.getSelectedItem()+";"+kayit_tarih.getSelectedItem();
            String kayidedilecek_bilgi12=ogrenci_no_bosluk.getText()+";"+sifre.getText()+";";
            String depolanacak_ogrenci_numara=ogrenci_no_bosluk.getText()+";";
            String kayidedilecek_deger=kayidedilecek_bilgi12+kayidedilecek_bilgi1+";"+kayidedilecek_bilgi2+";"+ kayidedilecek_bilgi22+";"+kayidedilecek_bilgi3+";"+kayidedilecek_bilgi4+";"+kayidedilecek_bilgi5+";"+kayidedilecek_bilgi6+";"+tarih+";"+kayidedilecek_bilgi10+";"+kayidedilecek_bilgi11+";";
            
            BilgiYaz(kayidedilecek_deger);
            islemler i=new islemler();
            i.setVisible(true);
            this.setVisible(false);
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane,"Lütfen Not Ortalamasını kontrol ediniz"); 
        }
        }
        else
        {
          JOptionPane.showMessageDialog(rootPane,"Lütfen Kayit yili  seciniz");  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alanMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_alanMouseClicked

    private void bitirme_tarihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bitirme_tarihMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_bitirme_tarihMouseClicked

    private void not_ortalamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_not_ortalamaMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_not_ortalamaMouseClicked

    private void bolumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bolumMouseClicked
         buyuk_harf();
    }//GEN-LAST:event_bolumMouseClicked

    private void kayit_tarihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_tarihMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_kayit_tarihMouseClicked

    private void sifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_sifreMouseClicked

    private void liseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liseMouseClicked
        buyuk_harf();
    }//GEN-LAST:event_liseMouseClicked

    private void oncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncekiActionPerformed
        yeni_kayit yk=new yeni_kayit();
        yk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_oncekiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeni_kayit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeni_kayit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeni_kayit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeni_kayit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeni_kayit1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akademik1;
    private javax.swing.JLabel akademik2;
    private javax.swing.JLabel akademik3;
    private javax.swing.JLabel akademik4;
    private javax.swing.JLabel akademik5;
    private javax.swing.JLabel akademik6;
    private javax.swing.JLabel akademik7;
    private javax.swing.JLabel akademik8;
    private javax.swing.JTextField alan;
    private javax.swing.JTextField bitirme_tarih;
    private javax.swing.JComboBox<String> bolum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> kayit_tarih;
    private javax.swing.JTextField lise;
    private javax.swing.JTextField not_ortalama;
    private javax.swing.JLabel ogrenci_no_bosluk;
    private javax.swing.JButton onceki;
    private javax.swing.JTextField sifre;
    private javax.swing.JLabel tarih;
    // End of variables declaration//GEN-END:variables
}
